---
sidebar: sidebar 
permalink: index.html 
summary: Bienvenue sur le portail de documentation de Cloud Insights. 
keywords:  
---
= Documentation Cloud Insights
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help
:toc-position: content


[role="lead"]
NetApp Cloud Insights est un outil de surveillance de l'infrastructure cloud qui permet de bénéficier d'une grande visibilité sur l'ensemble de l'infrastructure. Avec Cloud Insights, vous pouvez surveiller toutes les ressources, les optimiser et résoudre les problèmes, y compris dans les clouds publics et dans vos data centers privés.



== Que peut m'apporter Cloud Insights ?

Cloud Insights offre un contrôle multicloud hybride tout en garantissant l'observabilité de l'infrastructure et des charges de travail.

* Collecteurs de données pour infrastructure et workloads hétérogènes, y compris Kubernetes
* Ouvrez le collecteur Telegraf et les API ouvertes pour faciliter l'intégration
* Alertes et notifications complètes
* Machine learning pour des informations exploitables
* Optimisez l'utilisation des ressources
* Tableaux de bord intégrés ou personnalisables avec filtres avancés pour réduire le bruit d'affichage afin de répondre aux questions
* Découvrez l'état de santé des opérations de stockage ONTAP 
* Protégez vos ressources les plus précieuses : les données contre les attaques par ransomware ou les destructions de données


'''


== Mise en route

* Comment faire link:task_cloud_insights_onboarding_1.html["*lancez-vous*"] Avec Cloud Insights ?
* Je suis inscrit. Que dois-je faire maintenant ?link:task_getting_started_with_cloud_insights.html["Acquisition des données"]
link:concept_user_roles.html["Configuration des utilisateurs"]
* Génial ! Et la suite ?link:task_defining_annotations.html["Préparation des ressources : annotation"]
link:concept_querying_assets.html["Recherche des ressources que vous voulez : interrogation"]
link:concept_dashboards_overview.html["Voir les données que vous voulez : tableaux de bord"]
link:https:task_create_monitor.html["Surveillance et alertes"]
link:https://docs.netapp.com/us-en/cloudinsights/task_cs_getting_started.html["Sécurisation des données"]
* C'est super ! Je suis prêt à link:concept_subscribing_to_cloud_insights.html["*abonnez-vous*"].

