---
sidebar: sidebar 
permalink: task_troubleshooting_general_problems.html 
summary: Conseils généraux de dépannage de Cloud Insights. 
keywords: troubleshooting, problems, browser, login, log in, accessing, access to, Trident, qtree, quota 
---
= Dépannage des problèmes généraux de Cloud Insights
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Vous trouverez ici des suggestions de dépannage de Cloud Insights.

Voir aussi link:task_troubleshooting_linux_acquisition_unit_problems.html["Dépannage des problèmes d'unité d'acquisition Linux"] et link:task_troubleshooting_windows_acquisition_unit_problems.html["Dépannage des problèmes d'unité d'acquisition Windows"].



== Problèmes de connexion

|===
| *Problème:* | *Essayez ceci:* 


| Cloud Insights se déconnecte toutes les 5 minutes | 396149d67edd166e53b49c38f4b707ba 


| e4ff2e59dd571d2bbd5a906b6fad2546 | a9a216fbb1fb9d774e7cedfcf74c00cf 


| J'ai été invité à Cloud Insights mais j'ai reçu un message "non autorisé". | 199017f1d912993f091b6b969d3442ad 


| 176f8c6fa466059df49f2717c021d306 | 7a8624fb56224e907698f45ef2e4cc47 


| J'ai été automatiquement déconnecté après plusieurs jours. | ed6e79e2f9b9c201ed834c6efeb7f356 


| Je reçois un message d'erreur "n'est plus autorisé à se connecter". | acf29dcaa06698c29122cba5402e3145 


| Autres erreurs de connexion | Essayez le mode incognito dans Chrome ou effacez l'historique du navigateur, les cookies et le cache. Essayez avec un autre profil de navigateur (c.-à-d. Chrome - ajouter personne). 
|===


== Autres questions

|===


| *Question:* | *Réponse:* 


| Mes quotas matériels Qtree s'affichent correctement dans les requêtes, mais mes quotas souples s'affichent comme capacité totale du volume. Est-ce correct ? | Seuls les quotas matériels, définis manuellement ou définis via Trident, s'afficheront comme quotas définis ; si aucun quota matériel n'est spécifié, la capacité du volume interne sera la capacité du volume. 


| J'ai à la fois un quota souple et un quota matériel définis manuellement dans le même qtree, mais la capacité totale affichée est le quota dur ; est-ce correct ? | Oui, si un quota matériel est spécifié, il s'affichera comme la capacité totale. 


| Lors de la saisie d'un horaire de rapport Cognos, parfois, je me termine par un "m" supplémentaire dans l'horaire. Par exemple, si j'entre l'heure « 02:15 PM », il peut ajouter un caractère supplémentaire : « 02:15 PMM » (ou PMM). Lorsque je clique à l'extérieur, il passe à « 2:15 AM ».

Je suis capable d'enregistrer le rapport, mais lorsque je rouvre le rapport enregistré, l'heure de planification apparaît comme AM (c'est-à-dire matin), que je saisis AM ou PM dans l'heure de planification. | Entrez à nouveau l'heure programmée en veillant à ne pas entrer les caractères « AM » ou « PM » ; il suffit de taper « A » pour « AM » ou « P » pour « PM ». Si le caractère supplémentaire n'est pas affiché, l'heure de programmation sera définie correctement. 
|===


== Ressources

D'autres conseils de dépannage sont disponibles dans le link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights["Base de connaissances NetApp"] (connexion au support requise).

Vous trouverez d'autres informations de support dans le Cloud Insights link:concept_requesting_support.html["Assistance"] page.

Si vous disposez d'un abonnement Cloud Insights actif, vous pouvez utiliser les options de support suivantes :

link:https://www.netapp.com/us/contact-us/support.aspx["Téléphone"]
link:https://mysupport.netapp.com/site/cases/mine/create?serialNumber=95001014387268156333["Ticket de support"]

Pour plus d'informations, reportez-vous à la section https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html["Documentation de support Cloud Insights"].
