---
sidebar: sidebar 
permalink: task_dc_cohesity_smartfiles.html 
keywords: data collector, cohesity 
summary: Configuration du collecteur de données SmartFiles de Cohesity. 
---
= Le collecteur de données SmartFiles de Cohesity
:allow-uri-read: 


[role="lead"]
Ce collecteur BASÉ sur des API REST pourra acquérir un cluster Cohesity, découvrir les « vues » (sous la forme de volumes internes Cloud Insights), les différents nœuds, mais également collecter des metrics de performance.



== Configuration

[cols="2*"]
|===
| Champ | Description 


| Groupe d'instruments IP de Cohesity | Adresse IP du cluster Cohesity 


| Nom d'utilisateur | Nom d'utilisateur du cluster Cohesity 


| Mot de passe | Mot de passe utilisé pour le cluster Cohesity 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port utilisé pour la communication TCP avec le cluster Cohesity 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 60 minutes. 


| Intervalle d'interrogation des performances (min) | Intervalle entre les sondages de performances. La valeur par défaut est 900 secondes. 
|===


== Dépannage

Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
