---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers , Cloud Secure 
summary: Quelques étapes simples vous aideront à utiliser la sécurité de la charge de travail 
---
= Mise en route de la sécurité des charges de travail
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Certaines tâches de configuration doivent être effectuées avant de pouvoir utiliser la sécurité de la charge de travail pour surveiller l'activité des utilisateurs.


NOTE: La sécurité des charges de travail n'est pas disponible dans l'édition fédérale de Cloud Insights.

Le système Workload Security utilise un agent pour collecter les données d'accès des systèmes de stockage et des informations utilisateur à partir des serveurs Directory Services.

Vous devez configurer les éléments suivants avant de pouvoir commencer à collecter les données :

[cols="2*"]
|===


| Tâche | Informations associées 


| Configurer un agent  a| 
link:concept_cs_agent_requirements.html["Exigences de l'agent"]

link:task_cs_add_agent.html["Ajouter un agent"]

link:https://netapp.hubs.vidyard.com/watch/Lce7EaGg7NZfvCUw4Jwy5P?["*Vidéo* : déploiement de l'agent"]



| Configurer un connecteur de répertoire utilisateur | link:task_config_user_dir_connect.html["Ajouter un connecteur de répertoire utilisateur"]

link:https://netapp.hubs.vidyard.com/watch/NEmbmYrFjCHvPps7QMy8me?["*Vidéo* : connexion Active Directory"] 


| Configurer des collecteurs de données | Cliquez sur *Workload Security > Collectors*

Cliquez sur le collecteur de données à configurer.

Voir la section référence du fournisseur du Data Collector de la documentation.

link:https://netapp.hubs.vidyard.com/watch/YSQrcYA7DKXbj1UGeLYnSF?["*Vidéo* : connexion SVM ONTAP"] 


| Créer des comptes d'utilisateurs | link:concept_user_roles.html["Gérer les comptes d'utilisateurs"] 


| Dépannage | link:https://netapp.hubs.vidyard.com/watch/Fs8N2w9wBtsFGrhRH9X85U?["*Vidéo* : dépannage"] 
|===
La sécurité des charges de travail peut également s'intégrer à d'autres outils. Par exemple : link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["voir ce guide"] De l'intégration avec Splunk.
